@url=http://127.0.0.1:3001/api
@json = Content-Type: application/json


### 查看所有用户
GET {{url}}/users

### 注册
POST {{url}}/register
{{json}}

{
    "fullname" : "TianQi",
    "username":"user1",
    "password":"password",
    "age":24,
    "gender":"female",
    "email":"123@itmo.ru",
    "phone":"123312",
    "country":"China",
    "pet":"1 cat",
    "special":"Cleanliness Not sleep at night"
}

### 登录
POST {{url}}/login
{{json}}

{
    "username":"user1",
    "password":"password"
}


###return user
GET {{url}}/buildings


###return user
GET {{url}}/rooms?buildingId=61bd08627869a0fa8a18c911


###return user
GET {{url}}/
