@url=http://127.0.0.1:3001/api
@json = Content-Type: application/json


### 查看所有用户
GET {{url}}/users

### 注册
POST {{url}}/register
{{json}}

{
    "fullname" : "TianQi",
    "username":"user1",
    "password":"password",
    "age":24,
    "gender":"female",
    "email":"123@itmo.ru",
    "phone":"123312",
    "country":"China",
    "pet":"1 cat",
    "special":"Cleanliness Not sleep at night"
    
}

### 登录
POST {{url}}/login
{{json}}

{
    "username":"user1",
    "password":"password"
}


###return user
GET {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYmNjNzU1ZjkxZWZkZTU1YjkwNjc1MSIsImlhdCI6MTYzOTc2MTc1MX0.908GWGzd-3PWxjDQRjBDAd-dVQ9LLqkxHXGgoMLrthg